baseURL = 'https://all-messi.github.io/cir-library/'
languageCode = 'en-us'
title = 'Christian Internet Resources'
theme = 'scholarly'

[params]
  author = "Virgil Warren, PhD"
  description = "Christian Internet Resources (CIR) presents essays with interpersonalism (IP) in mind"
  siteName = "CIR"
  fullName = "Christian Internet Resources"
  mainSections = ["essays", "translations"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Essays"
    url = "/essays/"
    weight = 2
  [[menu.main]]
    name = "Text"
    url = "/translations/"
    weight = 3
  [[menu.main]]
    name = "Author"
    url = "/author/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"
  topic = "topics"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
